// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.0
// source: pkg/proto/summary/summary.proto

package summary

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GetSummary_GetSummary_FullMethodName = "/summary.GetSummary/GetSummary"
)

// GetSummaryClient is the client API for GetSummary service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetSummaryClient interface {
	GetSummary(ctx context.Context, in *SummaryRequest, opts ...grpc.CallOption) (*SummaryResponse, error)
}

type getSummaryClient struct {
	cc grpc.ClientConnInterface
}

func NewGetSummaryClient(cc grpc.ClientConnInterface) GetSummaryClient {
	return &getSummaryClient{cc}
}

func (c *getSummaryClient) GetSummary(ctx context.Context, in *SummaryRequest, opts ...grpc.CallOption) (*SummaryResponse, error) {
	out := new(SummaryResponse)
	err := c.cc.Invoke(ctx, GetSummary_GetSummary_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetSummaryServer is the server API for GetSummary service.
// All implementations must embed UnimplementedGetSummaryServer
// for forward compatibility
type GetSummaryServer interface {
	GetSummary(context.Context, *SummaryRequest) (*SummaryResponse, error)
	mustEmbedUnimplementedGetSummaryServer()
}

// UnimplementedGetSummaryServer must be embedded to have forward compatible implementations.
type UnimplementedGetSummaryServer struct {
}

func (UnimplementedGetSummaryServer) GetSummary(context.Context, *SummaryRequest) (*SummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSummary not implemented")
}
func (UnimplementedGetSummaryServer) mustEmbedUnimplementedGetSummaryServer() {}

// UnsafeGetSummaryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetSummaryServer will
// result in compilation errors.
type UnsafeGetSummaryServer interface {
	mustEmbedUnimplementedGetSummaryServer()
}

func RegisterGetSummaryServer(s grpc.ServiceRegistrar, srv GetSummaryServer) {
	s.RegisterService(&GetSummary_ServiceDesc, srv)
}

func _GetSummary_GetSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetSummaryServer).GetSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GetSummary_GetSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetSummaryServer).GetSummary(ctx, req.(*SummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GetSummary_ServiceDesc is the grpc.ServiceDesc for GetSummary service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetSummary_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "summary.GetSummary",
	HandlerType: (*GetSummaryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSummary",
			Handler:    _GetSummary_GetSummary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/summary/summary.proto",
}
