// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.0
// source: pkg/proto/subcategory.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubCategory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *SubCategory) Reset() {
	*x = SubCategory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_subcategory_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubCategory) ProtoMessage() {}

func (x *SubCategory) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_subcategory_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubCategory.ProtoReflect.Descriptor instead.
func (*SubCategory) Descriptor() ([]byte, []int) {
	return file_pkg_proto_subcategory_proto_rawDescGZIP(), []int{0}
}

func (x *SubCategory) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SubCategory) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetSubCategoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetSubCategoryRequest) Reset() {
	*x = GetSubCategoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_subcategory_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSubCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubCategoryRequest) ProtoMessage() {}

func (x *GetSubCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_subcategory_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubCategoryRequest.ProtoReflect.Descriptor instead.
func (*GetSubCategoryRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_subcategory_proto_rawDescGZIP(), []int{1}
}

func (x *GetSubCategoryRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetSubCategoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubCategory *SubCategory `protobuf:"bytes,1,opt,name=SubCategory,proto3" json:"SubCategory,omitempty"`
}

func (x *GetSubCategoryResponse) Reset() {
	*x = GetSubCategoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_subcategory_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSubCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubCategoryResponse) ProtoMessage() {}

func (x *GetSubCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_subcategory_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubCategoryResponse.ProtoReflect.Descriptor instead.
func (*GetSubCategoryResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_subcategory_proto_rawDescGZIP(), []int{2}
}

func (x *GetSubCategoryResponse) GetSubCategory() *SubCategory {
	if x != nil {
		return x.SubCategory
	}
	return nil
}

type GetSubCategoriesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []int32 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
}

func (x *GetSubCategoriesRequest) Reset() {
	*x = GetSubCategoriesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_subcategory_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSubCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubCategoriesRequest) ProtoMessage() {}

func (x *GetSubCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_subcategory_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubCategoriesRequest.ProtoReflect.Descriptor instead.
func (*GetSubCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_subcategory_proto_rawDescGZIP(), []int{3}
}

func (x *GetSubCategoriesRequest) GetIds() []int32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetSubCategoriesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubCategory []*SubCategory `protobuf:"bytes,1,rep,name=SubCategory,proto3" json:"SubCategory,omitempty"`
}

func (x *GetSubCategoriesResponse) Reset() {
	*x = GetSubCategoriesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_subcategory_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSubCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubCategoriesResponse) ProtoMessage() {}

func (x *GetSubCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_subcategory_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubCategoriesResponse.ProtoReflect.Descriptor instead.
func (*GetSubCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_subcategory_proto_rawDescGZIP(), []int{4}
}

func (x *GetSubCategoriesResponse) GetSubCategory() []*SubCategory {
	if x != nil {
		return x.SubCategory
	}
	return nil
}

type CreateSubCategoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreateSubCategoryRequest) Reset() {
	*x = CreateSubCategoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_subcategory_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSubCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubCategoryRequest) ProtoMessage() {}

func (x *CreateSubCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_subcategory_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubCategoryRequest.ProtoReflect.Descriptor instead.
func (*CreateSubCategoryRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_subcategory_proto_rawDescGZIP(), []int{5}
}

func (x *CreateSubCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateSubCategoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateSubCategoryResponse) Reset() {
	*x = CreateSubCategoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_subcategory_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSubCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubCategoryResponse) ProtoMessage() {}

func (x *CreateSubCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_subcategory_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubCategoryResponse.ProtoReflect.Descriptor instead.
func (*CreateSubCategoryResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_subcategory_proto_rawDescGZIP(), []int{6}
}

func (x *CreateSubCategoryResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteSubCategoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteSubCategoryRequest) Reset() {
	*x = DeleteSubCategoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_subcategory_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSubCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSubCategoryRequest) ProtoMessage() {}

func (x *DeleteSubCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_subcategory_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSubCategoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteSubCategoryRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_subcategory_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteSubCategoryRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteSubCategoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response bool `protobuf:"varint,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *DeleteSubCategoryResponse) Reset() {
	*x = DeleteSubCategoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_subcategory_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSubCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSubCategoryResponse) ProtoMessage() {}

func (x *DeleteSubCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_subcategory_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSubCategoryResponse.ProtoReflect.Descriptor instead.
func (*DeleteSubCategoryResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_subcategory_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteSubCategoryResponse) GetResponse() bool {
	if x != nil {
		return x.Response
	}
	return false
}

var File_pkg_proto_subcategory_proto protoreflect.FileDescriptor

var file_pkg_proto_subcategory_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x75, 0x62, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x31, 0x0a, 0x0b, 0x53, 0x75, 0x62, 0x43, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x27, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x53, 0x75,
	0x62, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x4e, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x0b, 0x53, 0x75,
	0x62, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x75, 0x62, 0x43, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x52, 0x0b, 0x53, 0x75, 0x62, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x22, 0x2b, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x69,
	0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0x50, 0x0a,
	0x18, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x0b, 0x53, 0x75, 0x62,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x75, 0x62, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x52, 0x0b, 0x53, 0x75, 0x62, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x22,
	0x2e, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x75, 0x62, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x2b, 0x0a, 0x19, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x75, 0x62, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2a, 0x0a, 0x18,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x75, 0x62, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x37, 0x0a, 0x19, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x53, 0x75, 0x62, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x32, 0xeb, 0x02, 0x0a, 0x0d, 0x53, 0x75, 0x62, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x69, 0x65, 0x73, 0x12, 0x4f, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x43, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65,
	0x74, 0x53, 0x75, 0x62, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x53,
	0x75, 0x62, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x55, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x12, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x58, 0x0a, 0x11, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x75, 0x62, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x12, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53,
	0x75, 0x62, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x53, 0x75, 0x62, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x58, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53,
	0x75, 0x62, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x1f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x75, 0x62, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x75, 0x62, 0x43, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x53, 0x61,
	0x75, 0x63, 0x79, 0x53, 0x61, 0x6c, 0x61, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x72, 0x2f, 0x6f, 0x77,
	0x6c, 0x2d, 0x64, 0x62, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_subcategory_proto_rawDescOnce sync.Once
	file_pkg_proto_subcategory_proto_rawDescData = file_pkg_proto_subcategory_proto_rawDesc
)

func file_pkg_proto_subcategory_proto_rawDescGZIP() []byte {
	file_pkg_proto_subcategory_proto_rawDescOnce.Do(func() {
		file_pkg_proto_subcategory_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_subcategory_proto_rawDescData)
	})
	return file_pkg_proto_subcategory_proto_rawDescData
}

var file_pkg_proto_subcategory_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pkg_proto_subcategory_proto_goTypes = []interface{}{
	(*SubCategory)(nil),               // 0: proto.SubCategory
	(*GetSubCategoryRequest)(nil),     // 1: proto.GetSubCategoryRequest
	(*GetSubCategoryResponse)(nil),    // 2: proto.GetSubCategoryResponse
	(*GetSubCategoriesRequest)(nil),   // 3: proto.GetSubCategoriesRequest
	(*GetSubCategoriesResponse)(nil),  // 4: proto.GetSubCategoriesResponse
	(*CreateSubCategoryRequest)(nil),  // 5: proto.CreateSubCategoryRequest
	(*CreateSubCategoryResponse)(nil), // 6: proto.CreateSubCategoryResponse
	(*DeleteSubCategoryRequest)(nil),  // 7: proto.DeleteSubCategoryRequest
	(*DeleteSubCategoryResponse)(nil), // 8: proto.DeleteSubCategoryResponse
}
var file_pkg_proto_subcategory_proto_depIdxs = []int32{
	0, // 0: proto.GetSubCategoryResponse.SubCategory:type_name -> proto.SubCategory
	0, // 1: proto.GetSubCategoriesResponse.SubCategory:type_name -> proto.SubCategory
	1, // 2: proto.SubCategories.GetSubCategory:input_type -> proto.GetSubCategoryRequest
	3, // 3: proto.SubCategories.GetSubCategories:input_type -> proto.GetSubCategoriesRequest
	5, // 4: proto.SubCategories.CreateSubCategory:input_type -> proto.CreateSubCategoryRequest
	7, // 5: proto.SubCategories.DeleteSubCategory:input_type -> proto.DeleteSubCategoryRequest
	2, // 6: proto.SubCategories.GetSubCategory:output_type -> proto.GetSubCategoryResponse
	4, // 7: proto.SubCategories.GetSubCategories:output_type -> proto.GetSubCategoriesResponse
	6, // 8: proto.SubCategories.CreateSubCategory:output_type -> proto.CreateSubCategoryResponse
	8, // 9: proto.SubCategories.DeleteSubCategory:output_type -> proto.DeleteSubCategoryResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_proto_subcategory_proto_init() }
func file_pkg_proto_subcategory_proto_init() {
	if File_pkg_proto_subcategory_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_subcategory_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubCategory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_subcategory_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSubCategoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_subcategory_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSubCategoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_subcategory_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSubCategoriesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_subcategory_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSubCategoriesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_subcategory_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSubCategoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_subcategory_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSubCategoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_subcategory_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSubCategoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_subcategory_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSubCategoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_subcategory_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_subcategory_proto_goTypes,
		DependencyIndexes: file_pkg_proto_subcategory_proto_depIdxs,
		MessageInfos:      file_pkg_proto_subcategory_proto_msgTypes,
	}.Build()
	File_pkg_proto_subcategory_proto = out.File
	file_pkg_proto_subcategory_proto_rawDesc = nil
	file_pkg_proto_subcategory_proto_goTypes = nil
	file_pkg_proto_subcategory_proto_depIdxs = nil
}
