// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.0
// source: pkg/proto/summary.proto

package summary

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SUMMARY_REPORT int32

const (
	SUMMARY_REPORT_All SUMMARY_REPORT = 0
)

// Enum value maps for SUMMARY_REPORT.
var (
	SUMMARY_REPORT_name = map[int32]string{
		0: "All",
	}
	SUMMARY_REPORT_value = map[string]int32{
		"All": 0,
	}
)

func (x SUMMARY_REPORT) Enum() *SUMMARY_REPORT {
	p := new(SUMMARY_REPORT)
	*p = x
	return p
}

func (x SUMMARY_REPORT) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SUMMARY_REPORT) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_summary_proto_enumTypes[0].Descriptor()
}

func (SUMMARY_REPORT) Type() protoreflect.EnumType {
	return &file_pkg_proto_summary_proto_enumTypes[0]
}

func (x SUMMARY_REPORT) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SUMMARY_REPORT.Descriptor instead.
func (SUMMARY_REPORT) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_summary_proto_rawDescGZIP(), []int{0}
}

type SummaryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SummaryReport SUMMARY_REPORT `protobuf:"varint,1,opt,name=summary_report,json=summaryReport,proto3,enum=proto.SUMMARY_REPORT" json:"summary_report,omitempty"`
}

func (x *SummaryRequest) Reset() {
	*x = SummaryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_summary_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryRequest) ProtoMessage() {}

func (x *SummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_summary_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryRequest.ProtoReflect.Descriptor instead.
func (*SummaryRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_summary_proto_rawDescGZIP(), []int{0}
}

func (x *SummaryRequest) GetSummaryReport() SUMMARY_REPORT {
	if x != nil {
		return x.SummaryReport
	}
	return SUMMARY_REPORT_All
}

type SummaryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SummaryResponse) Reset() {
	*x = SummaryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_summary_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryResponse) ProtoMessage() {}

func (x *SummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_summary_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryResponse.ProtoReflect.Descriptor instead.
func (*SummaryResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_summary_proto_rawDescGZIP(), []int{1}
}

func (x *SummaryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_proto_summary_proto protoreflect.FileDescriptor

var file_pkg_proto_summary_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x75, 0x6d, 0x6d,
	0x61, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x4f, 0x0a, 0x0f, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x5f, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x3c, 0x0a, 0x0e, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x5f, 0x72,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x55, 0x4d, 0x4d, 0x41, 0x52, 0x59, 0x5f, 0x52, 0x45, 0x50, 0x4f,
	0x52, 0x54, 0x52, 0x0d, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x22, 0x2c, 0x0a, 0x10, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x5f, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2a,
	0x19, 0x0a, 0x0e, 0x53, 0x55, 0x4d, 0x4d, 0x41, 0x52, 0x59, 0x5f, 0x52, 0x45, 0x50, 0x4f, 0x52,
	0x54, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x6c, 0x6c, 0x10, 0x00, 0x32, 0x4d, 0x0a, 0x0a, 0x47, 0x65,
	0x74, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x3f, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x53,
	0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x73,
	0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x5f, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x53, 0x61, 0x75, 0x63, 0x79, 0x53, 0x61, 0x6c,
	0x61, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x72, 0x2f, 0x6f, 0x77, 0x6c, 0x2d, 0x64, 0x62, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_summary_proto_rawDescOnce sync.Once
	file_pkg_proto_summary_proto_rawDescData = file_pkg_proto_summary_proto_rawDesc
)

func file_pkg_proto_summary_proto_rawDescGZIP() []byte {
	file_pkg_proto_summary_proto_rawDescOnce.Do(func() {
		file_pkg_proto_summary_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_summary_proto_rawDescData)
	})
	return file_pkg_proto_summary_proto_rawDescData
}

var file_pkg_proto_summary_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_proto_summary_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_proto_summary_proto_goTypes = []interface{}{
	(SUMMARY_REPORT)(0),     // 0: proto.SUMMARY_REPORT
	(*SummaryRequest)(nil),  // 1: proto.summary_request
	(*SummaryResponse)(nil), // 2: proto.summary_response
}
var file_pkg_proto_summary_proto_depIdxs = []int32{
	0, // 0: proto.summary_request.summary_report:type_name -> proto.SUMMARY_REPORT
	1, // 1: proto.GetSummary.GetSummary:input_type -> proto.summary_request
	2, // 2: proto.GetSummary.GetSummary:output_type -> proto.summary_response
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_proto_summary_proto_init() }
func file_pkg_proto_summary_proto_init() {
	if File_pkg_proto_summary_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_summary_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SummaryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_summary_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SummaryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_summary_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_summary_proto_goTypes,
		DependencyIndexes: file_pkg_proto_summary_proto_depIdxs,
		EnumInfos:         file_pkg_proto_summary_proto_enumTypes,
		MessageInfos:      file_pkg_proto_summary_proto_msgTypes,
	}.Build()
	File_pkg_proto_summary_proto = out.File
	file_pkg_proto_summary_proto_rawDesc = nil
	file_pkg_proto_summary_proto_goTypes = nil
	file_pkg_proto_summary_proto_depIdxs = nil
}
